cabal-version:   3.0
name:            haskell-book-interactive
version:         0.1.0.0
license:         BSD-3-Clause
build-type:      Simple
license-file:    LICENSE
author:          Tyrn
maintainer:      Tyrn <a@b.com>
copyright:       2024 Tyrn
-- tested-with:     GHC ==8.6.5 || ==8.8.3 || ==8.10.7 || ==9.0.2 || ==9.2.2
extra-doc-files:
  CHANGELOG.md
  README.md

common common-options
  -- build-depends:    base >=4.9 && <5
  build-depends:
    , base ^>=4.20.2.0
    , string-interpolate ^>= 0.3
  default-language: GHC2024
  ghc-options:
    -Wall -Wcompat -Widentities -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Wredundant-constraints
    -fhide-source-paths -Wpartial-fields

library
  import:          common-options
  hs-source-dirs:  src
  exposed-modules:  Ch02, Ch03, Ch04, Ch05
  other-modules:   Paths_haskell_book_interactive
  build-depends:
    , containers
    , turtle
    , mtl
    , process
    , temporary
    , exceptions
    , extra
    , filepath
    , unix-compat
    , doctest
    , regex-tdfa
    , text
    , bytestring
    , directory
    , foldl
    , htaglib

executable haskell-book-interactive
  import:         common-options
  hs-source-dirs: app
  main-is:        Main.hs
  build-depends:
    , haskell-book-interactive
    , turtle
    , mtl
    , text
    , foldl
    , extra
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N

test-suite haskell-book-interactive-test
  import:         common-options
  type:           exitcode-stdio-1.0
  hs-source-dirs: test
  main-is:        Spec.hs
  other-modules:  Ch02Spec, Ch03Spec, Ch04Spec, Ch05Spec
  build-depends:
    , hspec
    , hspec-expectations
    , doctest
    , text
    , regex-tdfa
    , filepath
    , HUnit
    , haskell-book-interactive
    , QuickCheck
  build-tool-depends:
--    , calligraphy:calligraphy
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N

test-suite doctests
  import:         common-options
  type:           exitcode-stdio-1.0
  hs-source-dirs: test
  main-is:        Doctest.hs
  build-depends:
    , base
    , doctest
    , directory
    , filepath
    , haskell-book-interactive
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N
